FROM python:3.10-slim

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends wget ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

COPY requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir -r /src/requirements.txt

# Yandex Cloud managed services CA certificate
RUN mkdir -p /crt \
    && wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt \
    && chmod 0600 /crt/YandexInternalRootCA.crt

COPY src/ /src/

ENTRYPOINT ["python"]
CMD ["app.py"]
